server:
  port: 8000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/C410lol/adega-requinte-backend/tree/main/adega-config-files
        vault:
          authentication: TOKEN
          host: 127.0.0.1
          kv-version: 2
          port: 8200
          token: hvsr3JHoO4vzBmpkxsOg2Emn3xg
  profiles:
    active: git, vault
