eureka:
  client:
    defaultZone: http://localhost:8761
    fetch-register: true
    register-with-eureka: true

server:
  port: 6060

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adega-products-db
  jpa:
    hibernate:
      ddl-auto: update 
