eureka:
  client:
    defaultZone: http://localhost:8761
    fetch-register: true
    register-with-eureka: true

server:
  port: 5050

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adega-users-db
  jpa:
    hibernate:
      ddl-auto: update
