eureka:
  client:
    fetch-register: true
    register-with-eureka: true
    defaultZone: http://localhost:8761

server:
  port: 7000

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: ADEGA-PRODUCTS-SERVICE
          uri: lb://ADEGA-PRODUCTS-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - JwtFilter
        - id: ADEGA-USERS-SERVICE
          uri: lb://ADEGA-USERS-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - JwtFilter
        - id: ADEGA-ORDERS-SERVICE
          uri: lb://ADEGA-ORDERS-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - JwtFilter
            
